openapi: 3.0.1
info:
  title: Order Management API
  description: Dominos Order Management API
  version: "1.0.0"
  contact:
    name: Dominos
    url: http://www.dominos.html
    email: dominos@d.com
servers:
  - url: http://localhost:20021
    description: Generated server url
#tags:
#  - name: user
#    description: Operations about user
#    externalDocs:
#      description: Find out more about our store
#      url: http://swagger.io
paths:
  /menu:
    get:
      tags:
        - menu
      summary: Get menu items
      operationId: getMenu
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        404:
          description: Menu not found
          content: {}
  /menu/{menuId}:
    get:
      tags:
        - menu
      summary: Get menu items by menu id
      operationId: getMenu_1
      parameters:
        - name: menuId
          in: path
          description: 'The name that needs to be fetched. '
          required: true
          schema:
            type: integer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        404:
          description: Menu not found
          content: { }
components:
  schemas:
    MainMenu:
      type: object
      properties:
        id:
          type: integer
          format: int64
        menuType:
          type: array
          items:
            $ref: '#/components/schemas/MenuType'
        description:
          type: string
    MenuType:
      type: object
      properties:
        id:
          type: integer
        subMenu:
          type: array
          items:
            $ref: '#/components/schemas/SubMenu'
        description:
          type: string
    SubMenu:
      type: object
      properties:
        id:
          type: integer
        subMenuItems:
          type: array
          items:
            type: string
        description:
          type: string
    Response:
      type: object
      properties:
        result:
          type: object
        description:
          type: string
        statusCode:
          type: integer
  securitySchemes:
    reflectoring_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://reflectoring.swagger.io/oauth/dialog
          scopes:
            write:users: modify users
            read:users: read users
    api_key:
      type: apiKey
      name: api_key
      in: header